#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
#
## Liferay Portal deployment directory, its the core portal and not the plugins
#
_LIFERAY_PORTAL_DEPLOY_DIR="${OPENSHIFT_DATA_DIR}liferay"
echo "LIFERAY PORTAL REFRESH AFTER 'configuration updates/new plugins deplyment in last push'"
touch ${_LIFERAY_PORTAL_DEPLOY_DIR}/ROOT.war.dodeploy
echo "Please wait as, portal deployment refresh will take from 2-5 minutes"
